apiVersion: v1
kind: ServiceAccount
metadata:
  name: pkg-gitops-app-sa
  namespace: pkg-gitops
  annotations:
    kapp.k14s.io/change-group: "rbac"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting namespace"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting namespace"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-cluster-role-app
  annotations:
    kapp.k14s.io/change-group: "rbac"
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-cluster-role-binding-app
  annotations:
    kapp.k14s.io/change-group: "rbac"
subjects:
- kind: ServiceAccount
  name: pkg-gitops-app-sa
  namespace: pkg-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin-cluster-role-app
